# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: YoloWorldService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16YoloWorldService.proto\"\x82\x01\n\nObjectData\x12\x0f\n\x07\x43lassId\x18\x01 \x01(\x05\x12\x12\n\nConfidence\x18\x02 \x01(\x01\x12\x0f\n\x07\x43\x65nterX\x18\x03 \x01(\x01\x12\x0f\n\x07\x43\x65nterY\x18\x04 \x01(\x01\x12\x15\n\rBoundingWidth\x18\x05 \x01(\x01\x12\x16\n\x0e\x42oundingHeight\x18\x06 \x01(\x01\"M\n\x10\x44\x65tectionRequest\x12\x12\n\nClientName\x18\x01 \x01(\t\x12\x12\n\nClassNames\x18\x02 \x03(\t\x12\x11\n\tJpegImage\x18\x03 \x01(\x0c\"1\n\x11\x44\x65tectionResponse\x12\x1c\n\x07Objects\x18\x01 \x03(\x0b\x32\x0b.ObjectData\"I\n\x0cLabelRequest\x12\x12\n\nClientName\x18\x01 \x01(\t\x12\x12\n\nClassNames\x18\x02 \x03(\t\x12\x11\n\tJpegImage\x18\x03 \x01(\x0c\"\"\n\rLabelResponse\x12\x11\n\tJpegImage\x18\x01 \x01(\x0c\x32k\n\x10YoloWorldService\x12/\n\x06\x44\x65tect\x12\x11.DetectionRequest\x1a\x12.DetectionResponse\x12&\n\x05Label\x12\r.LabelRequest\x1a\x0e.LabelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'YoloWorldService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTDATA']._serialized_start=27
  _globals['_OBJECTDATA']._serialized_end=157
  _globals['_DETECTIONREQUEST']._serialized_start=159
  _globals['_DETECTIONREQUEST']._serialized_end=236
  _globals['_DETECTIONRESPONSE']._serialized_start=238
  _globals['_DETECTIONRESPONSE']._serialized_end=287
  _globals['_LABELREQUEST']._serialized_start=289
  _globals['_LABELREQUEST']._serialized_end=362
  _globals['_LABELRESPONSE']._serialized_start=364
  _globals['_LABELRESPONSE']._serialized_end=398
  _globals['_YOLOWORLDSERVICE']._serialized_start=400
  _globals['_YOLOWORLDSERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
